" Forget being compatible with good ol' vi
set nocompatible

" Pathogen initialization
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

set hidden                        " Allow vim to manage multiple buffers effective
set history=1000                  " Bigger command history

set showcmd		                  " Display incomplete commands.
set showmode                      " Shows the mode we're in

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell

set backspace=indent,eol,start    " Intuitive backspacing.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

" Store temporary files in a central spot
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set hlsearch                      " Highlight searches
set incsearch                     " ... dynamically as they are typed
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
nmap <leader>n :set hls!<CR>

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P\ (of\ %L)

" Invisible character symbols
set listchars=tab:▸\ ,eol:¬
nmap <leader>l :set list!<CR>

" On changing replacing mode put a $ sign at the end
set cpoptions+=$

" Default whitespace for all files
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab

" Vim should always run from the shell (RVM Support)
set shell=/bin/sh

" Enable spellchecking for txt files
autocmd FileType txt set spell spelllang=en,el

" Custom whitespace
autocmd FileType ruby  setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType eruby setlocal ts=4 sts=4 sw=4 expandtab
autocmd FileType yaml  setlocal ts=2 sts=2 sw=2 expandtab
" 
autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
" 
autocmd FileType html setlocal ts=4 sts=4 sw=4 expandtab
autocmd FileType css setlocal ts=4 sts=2 sw=4 expandtab
autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab

" Mappings for moving lines up and down.
nmap <C-j> :m+<CR>
imap <C-j> <Esc>:m+<CR>
vmap <C-j> :m'>+<CR>gv
nmap <C-k> :m-2<CR>
imap <C-k> <Esc>:m-2<CR>
vmap <C-k> :m-2<CR>gv

" Set colorscheme to ir_black for terminal
colorscheme ir_black

" If there is a GUI
if has("gui_macvim")
	" Set the colorscheme
	colorscheme monokai_customized
	set guifont=AnonymousPro:h13 " Change font

	" Change color scheme for ruby files
	" autocmd FileType ruby,eruby colorscheme railscasts
	" Default dimensions for a new window
	set lines=80 columns=120

	" Full screen options for capturing full horizontal and vertical space
	set fuoptions=maxvert,maxhorz
	map <leader>f :set fullscreen!<CR>

	" GUI customization
	set go-=T " Remove toolbar
	" Remove vertical scrolling from both sides
	set guioptions-=r
	set guioptions-=L

	" Transparency
	set transparency=5
endif

" Plugins

" NERD Tree
nmap <leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>

" NERD Commenter
" Add an extra space after the left delimeter
let NERDSpaceDelims=1

" Command-/ to toggle comments
map <D-/> <plug>NERDCommenterToggle<CR>

" Fuzzy Finder
nmap <leader>b :FufBuffer<CR>
